### ISSUE TITLE
importing into gcal creates extraneous events on the first day

### ISSUE THREAD

**Issue by ianklatzco** [rmmh/uiuccalendar#1]
thank you very much for this, it's been very useful

eg: the 313 and 391 on tues are not supposed to be there
![image](https://cloud.githubusercontent.com/assets/1487413/22004764/0062a1ea-dc24-11e6-8205-e8cac81506fa.png)

**Comment by ianklatzco** [comment]
from this input:

```
46634	ART 199 GD	Painting & Collage Experiments	Urbana-Champaign	3.000	1U	Jan 17, 2017	May 03, 2017	TR	9:00 am - 10:50 am	Art and Design Building 330	Davies
57810	CHLH 206 ONL	Human Sexuality	Urbana-Champaign	2.000	1U	Mar 13, 2017	May 03, 2017	 	TBA	TBA	Rinaldi-Miles
63846	CLCV 220 D	The Animal Self	Urbana-Champaign	3.000	1U	Jan 17, 2017	May 03, 2017	TR	11:00 am - 12:20 pm	1205 W Oregon 212	Williams
65543	ECE 313 G	Probability with Engrg Applic	Urbana-Champaign	3.000	1U	Jan 17, 2017	May 03, 2017	MW	11:00 am - 12:20 pm	Siebel Center for Comp Sci 0216	Iyer
47024	ECE 391 AD3	Computer Systems Engineering	Urbana-Champaign	0.000	1U	Jan 17, 2017	May 03, 2017	W	1:00 pm - 1:50 pm	Electrical & Computer Eng Bldg 3026	TBA
45210	ECE 391 AL	Computer Systems Engineering	Urbana-Champaign	4.000	1U	Jan 17, 2017	May 03, 2017	TR	2:00 pm - 3:20 pm	Electrical & Computer Eng Bldg 1002	Kalbarczyk
40130	LING 406 U3	Intro to Computational Ling	Urbana-Champaign	3.000	1U	Jan 17, 2017	May 03, 2017	TR	12:30 pm - 1:50 pm	Engineering Hall 106B1	Girju
```

**Comment by rmmh** [comment]
It's a problem with how DTSTART and the repeat rule interact. The first event occurs on the first day the class is defined, and then it repeats on MW through the end of the semester.

    DTSTART;TZID=America/Chicago:20170117T110000
    DTEND;TZID=America/Chicago:20170117T122000
    RRULE:FREQ=WEEKLY;WKST=MO;UNTIL=20170503T235900;BYDAY=MO,WE

**Comment by rmmh** [comment]
Should be fixed now! ![image](https://cloud.githubusercontent.com/assets/211868/22016336/c6badd90-dc5a-11e6-8613-773967746174.png)

Good luck with your 9AM class :-)
